project:
  type: website

website:
  title: "Macro"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Getting Started
        file: getting-started.qmd
      - text: FAQ
        file: faq.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Inflation"
        href: basics-summary.qmd
        contents:
          - cpi.qmd
          - pce.qmd
          - deflator.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: advanced.qmd
        contents:
          - raw-code.qmd
          - custom-theme.qmd
      - acknowlegment.qmd
format:
  html:
    theme: cosmo
    toc: true


